### ISSUE TITLE
Question about visibility

### ISSUE THREAD

**Issue by bmulcahy** [simme/ampersand-modal-view#1]
I added the modal to my document using the default body container. When I go to open the modal I can see that it has been added, but for some reason it is not visible when viewing the document.

```
<div role="dialog" aria-hidden="true" aria-describedby="amp-modal-descr" data-hook="overlay" class="modal-overlay" style="display: block;">
<div class="modal-body" tabindex="0" role="document">
<button class="close" data-hook="close">
<span aria-hidden="true">×</span>
<span class="screenreader" data-hook="close-text">Close</span>
</button>
<h1 data-hook="title">Title of My Modal</h1>
<p id="amp-modal-descr" data-hook="description">a description, mostly for screenreaders</p>
<div data-hook="content"><p>One fine body…</p></div>
</div>
</div>

```

I notice the aria-hidden="true" is this what is causing it?

edit: I changed the container to render in and it is viewable but it inherited all the css of the parent container. I will work on it some more this is just user error I have a feeling.

**Comment by simme** [comment]
Yeah, you have to write all of the CSS yourself. That might be your issue. Let me know if there are any parts of the documentation that I could make more obvious! :)

**Comment by bmulcahy** [comment]
Yea I figured that out now. Is there anyway to include maybe the default css styles and functions from bootstrap's modal?

**Comment by simme** [comment]
I don't think the modal will ever include default CSS. This is a JavaScript module only. :) But I might provide some example CSS in the README!
